language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - nightly
  - hhvm

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly
    - php: hhvm

before_script:
   - composer install --dev

script:
   - phpunit -c test/
   - php -d zend.enable_gc=0 ./vendor/bin/php-cs-fixer fix -v --dry-run;
